import { ShieldCheck } from 'lucide-react'
import type { PolicySection } from '@/types'

interface GeneratorPreviewProps {
  title: string
  sections: PolicySection[]
  companyName?: string
  effectiveDate?: string
}

export function GeneratorPreview({ title, sections, companyName, effectiveDate }: GeneratorPreviewProps) {
  const dateLabel = effectiveDate
    ? new Date(effectiveDate + 'T00:00:00').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  return (
    <div className="bg-white dark:bg-gray-950 rounded-2xl border border-gray-200 dark:border-gray-800 overflow-hidden">
      {/* Preview header bar */}
      <div className="flex items-center gap-1.5 px-4 py-2.5 bg-gray-50 dark:bg-gray-900 border-b border-gray-100 dark:border-gray-800">
        <div className="size-2.5 rounded-full bg-red-400" />
        <div className="size-2.5 rounded-full bg-amber-400" />
        <div className="size-2.5 rounded-full bg-green-400" />
        <div className="flex-1 mx-2 h-5 bg-white dark:bg-gray-800 rounded text-xs text-gray-400 flex items-center px-2 font-mono truncate">
          openprivacypolicy.com/p/preview
        </div>
      </div>

      {/* Policy content */}
      <div className="p-5 max-h-[calc(100vh-280px)] overflow-y-auto">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-2">
            <ShieldCheck className="size-3.5 text-brand-500" />
            <span>Privacy Policy</span>
            {companyName && (
              <>
                <span>·</span>
                <span>{companyName}</span>
              </>
            )}
          </div>
          <h1 className="text-lg font-bold text-gray-900 dark:text-white tracking-tight mb-1">
            {title || 'Privacy Policy'}
          </h1>
          <p className="text-xs text-gray-400">Effective: {dateLabel}</p>
        </div>

        {/* Table of contents */}
        {sections.length > 0 && (
          <nav className="mb-6 p-3 bg-gray-50 dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800">
            <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2">
              Contents
            </p>
            <ol className="space-y-1">
              {sections.map((s, i) => (
                <li key={s.id}>
                  <a
                    href={`#prev-${s.id}`}
                    className="text-xs text-brand-600 dark:text-brand-400 hover:text-brand-800 flex gap-1.5"
                  >
                    <span className="text-gray-300 dark:text-gray-600 font-mono">{(i + 1).toString().padStart(2, '0')}.</span>
                    {s.title}
                  </a>
                </li>
              ))}
            </ol>
          </nav>
        )}

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section, i) => (
            <section key={section.id} id={`prev-${section.id}`} className="scroll-mt-4">
              <h2 className="text-sm font-semibold text-gray-900 dark:text-white mb-2 flex items-center gap-1.5">
                <span className="text-xs font-mono text-gray-300 dark:text-gray-600">
                  {(i + 1).toString().padStart(2, '0')}
                </span>
                {section.title}
              </h2>
              <p className="text-xs leading-6 text-gray-600 dark:text-gray-400 whitespace-pre-wrap">
                {section.content}
              </p>
            </section>
          ))}
        </div>

        {sections.length === 0 && (
          <div className="py-16 text-center">
            <ShieldCheck className="size-8 text-gray-200 dark:text-gray-700 mx-auto mb-3" />
            <p className="text-sm text-gray-400">Fill in the form to see your policy preview</p>
          </div>
        )}

        {/* Watermark footer */}
        {sections.length > 0 && (
          <div className="mt-8 pt-4 border-t border-gray-100 dark:border-gray-800 text-center">
            <p className="text-xs text-gray-300 dark:text-gray-600">Generated by OpenPrivacyPolicy</p>
          </div>
        )}
      </div>
    </div>
  )
}
