import { useMemo, useState, useCallback } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Eye, EyeOff, RotateCcw, ShieldCheck, FolderOpen, Plus } from 'lucide-react'
import toast from 'react-hot-toast'

import { Logo } from '@/components/ui/Logo'
import { Button } from '@/components/ui/Button'
import { ThemeToggle } from '@/components/ui/ThemeToggle'
import { usePolicyStore } from '@/store/policyStore'
import { useGeneratorStore } from '@/store/generatorStore'
import { generatePolicySections, generatePolicyTitle } from '@/utils/policyGenerator'
import { trackEvent } from '@/utils/analytics'
import { cn } from '@/utils/cn'

import { StepIndicator } from './StepIndicator'
import { GeneratorPreview } from './GeneratorPreview'
import { MyPoliciesPanel } from './MyPoliciesPanel'
import { PolicyEditor } from './PolicyEditor'
import { BasicInfoStep } from './steps/BasicInfoStep'
import { DataCollectionStep } from './steps/DataCollectionStep'
import { DataUsageStep } from './steps/DataUsageStep'
import { UserRightsStep } from './steps/UserRightsStep'
import { ReviewStep } from './steps/ReviewStep'
import type { PolicySection } from '@/types'

type PageView = 'generator' | 'my-policies' | { type: 'edit'; policyId: string }

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())
}

function isValidUrl(url: string): boolean {
  if (!url.trim()) return true
  try { new URL(url.trim()); return true } catch { return false }
}

function PrintView({ title, sections, companyName, effectiveDate }: {
  title: string; sections: PolicySection[]; companyName?: string; effectiveDate?: string
}) {
  const dateLabel = effectiveDate
    ? new Date(effectiveDate + 'T00:00:00').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  return (
    <div className="hidden print:block fixed inset-0 bg-white z-[9999] p-[2cm] overflow-visible">
      <div className="mb-8">
        <div className="flex items-center gap-2 text-sm text-gray-400 mb-3">
          <ShieldCheck className="size-4" style={{ color: '#5b73f5' }} />
          <span>Privacy Policy</span>
          {companyName && <><span>·</span><span>{companyName}</span></>}
        </div>
        <h1 style={{ fontSize: '28px', fontWeight: '700', marginBottom: '6px', color: '#111827' }}>{title}</h1>
        <p style={{ fontSize: '13px', color: '#9ca3af' }}>Effective: {dateLabel}</p>
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
        {sections.map((section, i) => (
          <div key={section.id}>
            <h2 style={{ fontSize: '15px', fontWeight: '600', color: '#111827', marginBottom: '8px' }}>
              <span style={{ fontFamily: 'monospace', fontSize: '11px', color: '#d1d5db', marginRight: '8px' }}>
                {(i + 1).toString().padStart(2, '0')}
              </span>
              {section.title}
            </h2>
            <p style={{ fontSize: '12px', lineHeight: '1.8', color: '#4b5563', whiteSpace: 'pre-wrap' }}>
              {section.content}
            </p>
          </div>
        ))}
      </div>
      <div style={{ marginTop: '40px', paddingTop: '16px', borderTop: '1px solid #f3f4f6', textAlign: 'center' }}>
        <p style={{ fontSize: '10px', color: '#d1d5db' }}>Generated by OpenPrivacyPolicy · openprivacypolicy.com</p>
      </div>
    </div>
  )
}

export function PolicyGeneratorPage() {
  const navigate = useNavigate()
  const { currentStep, formData, setStep, updateFormData, reset } = useGeneratorStore()
  const { createPolicy, policies } = usePolicyStore()
  const [view, setView] = useState<PageView>('generator')
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [previewOpen, setPreviewOpen] = useState(false)
  const [publishing, setPublishing] = useState(false)

  const sections = useMemo(() => generatePolicySections(formData), [formData])
  const policyTitle = useMemo(() => generatePolicyTitle(formData), [formData])

  const validateStep = useCallback((step: number): boolean => {
    const errs: Record<string, string> = {}
    if (step === 0) {
      if (!formData.appName.trim()) errs.appName = 'App name is required'
      if (!formData.companyName.trim()) errs.companyName = 'Company name is required'
      if (!formData.contactEmail.trim()) errs.contactEmail = 'Contact email is required'
      else if (!isValidEmail(formData.contactEmail)) errs.contactEmail = 'Enter a valid email address'
      if (!formData.effectiveDate) errs.effectiveDate = 'Effective date is required'
      if (formData.websiteUrl && !isValidUrl(formData.websiteUrl)) errs.websiteUrl = 'Enter a valid URL (e.g. https://yoursite.com)'
    }
    setErrors(errs)
    return Object.keys(errs).length === 0
  }, [formData])

  function handleNext() {
    if (validateStep(currentStep)) {
      setStep(currentStep + 1)
      setErrors({})
      window.scrollTo({ top: 0, behavior: 'smooth' })
    }
  }

  function handleBack() {
    setStep(currentStep - 1)
    setErrors({})
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  function handleStepClick(step: number) {
    setStep(step)
    setErrors({})
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  function handleExportPDF() {
    trackEvent('generator_pdf_exported', { appName: formData.appName })
    window.print()
  }

  function handleExportJSON() {
    const payload = {
      title: policyTitle,
      appName: formData.appName,
      companyName: formData.companyName,
      contactEmail: formData.contactEmail,
      websiteUrl: formData.websiteUrl || undefined,
      effectiveDate: formData.effectiveDate,
      generatedAt: new Date().toISOString(),
      generatedBy: 'OpenPrivacyPolicy Generator — openprivacypolicy.com',
      sections: sections.map(({ id, title, content }) => ({ id, title, content })),
    }
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${formData.appName.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'privacy-policy'}-privacy-policy.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    trackEvent('generator_json_exported', { appName: formData.appName })
    toast.success('JSON file downloaded')
  }

  function handlePublish() {
    if (!formData.appName.trim() || !formData.contactEmail.trim()) {
      toast.error('Please fill in app name and contact email first.')
      setStep(0)
      return
    }
    setPublishing(true)
    try {
      const policy = createPolicy({
        title: policyTitle,
        sections,
        companyName: formData.companyName,
        websiteUrl: formData.websiteUrl || undefined,
        contactEmail: formData.contactEmail,
        status: 'published',
        publishedAt: new Date().toISOString(),
      })
      trackEvent('generator_policy_published', { appName: formData.appName })
      toast.success('Preview link created!')
      reset()
      navigate(`/p/${policy.slug}`)
    } catch {
      toast.error('Something went wrong. Please try again.')
      setPublishing(false)
    }
  }

  function handleReset() {
    if (window.confirm('Reset all progress? This will clear your saved form data.')) {
      reset()
      setErrors({})
    }
  }

  const hasSavedProgress = formData.appName.trim() !== '' || currentStep > 0
  const isGenerator = view === 'generator'
  const isMyPolicies = view === 'my-policies'
  const editingPolicy = typeof view === 'object' && view.type === 'edit' ? view.policyId : null

  return (
    <>
      <PrintView
        title={policyTitle}
        sections={sections}
        companyName={formData.companyName}
        effectiveDate={formData.effectiveDate}
      />

      <div className="min-h-screen bg-gray-50 dark:bg-gray-950 print:hidden overflow-x-hidden">
        {/* Header */}
        <header className="sticky top-0 z-20 bg-white/90 dark:bg-gray-950/90 backdrop-blur border-b border-gray-100 dark:border-gray-800">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <Link to="/">
                <Logo size="sm" />
              </Link>
              <span className="text-gray-300 dark:text-gray-700">/</span>

              {/* View tabs */}
              <nav className="flex items-center gap-0.5">
                <button
                  type="button"
                  onClick={() => { setView('generator'); window.scrollTo({ top: 0 }) }}
                  className={cn(
                    'flex items-center gap-1.5 h-8 px-3 rounded-lg text-sm font-medium transition-colors',
                    isGenerator
                      ? 'bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white'
                      : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'
                  )}
                >
                  <Plus className="size-3.5" />
                  <span className="hidden sm:inline">New policy</span>
                  <span className="sm:hidden">New</span>
                </button>
                <button
                  type="button"
                  onClick={() => { setView('my-policies'); window.scrollTo({ top: 0 }) }}
                  className={cn(
                    'flex items-center gap-1.5 h-8 px-3 rounded-lg text-sm font-medium transition-colors',
                    (isMyPolicies || editingPolicy)
                      ? 'bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white'
                      : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'
                  )}
                >
                  <FolderOpen className="size-3.5" />
                  <span className="hidden sm:inline">My policies</span>
                  <span className="sm:hidden">Policies</span>
                  {policies.length > 0 && (
                    <span className={cn(
                      'text-xs rounded-full px-1.5 py-0 font-medium min-w-[18px] text-center',
                      (isMyPolicies || editingPolicy)
                        ? 'bg-brand-600 text-white'
                        : 'bg-gray-200 dark:bg-gray-700 text-gray-600 dark:text-gray-400'
                    )}>
                      {policies.length}
                    </span>
                  )}
                </button>
              </nav>
            </div>

            <div className="flex items-center gap-2">
              {isGenerator && hasSavedProgress && (
                <>
                  <span className="hidden sm:inline text-xs bg-green-50 dark:bg-green-950/30 text-green-600 dark:text-green-400 px-2 py-1 rounded-full border border-green-200 dark:border-green-900">
                    Progress saved
                  </span>
                  <button
                    type="button"
                    onClick={handleReset}
                    className="text-xs text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 flex items-center gap-1 transition-colors"
                  >
                    <RotateCcw className="size-3" />
                    <span className="hidden sm:inline">Reset</span>
                  </button>
                </>
              )}
              <ThemeToggle />
            </div>
          </div>
        </header>

        {/* Generator view */}
        {isGenerator && (
          <>
            <StepIndicator currentStep={currentStep} onStepClick={handleStepClick} />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4 sm:py-6 lg:py-8">
              <div className="lg:grid lg:grid-cols-[1fr_400px] lg:gap-6 xl:grid-cols-[1fr_440px]">
                {/* Form panel */}
                <div>
                  <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 p-4 sm:p-8">
                    {currentStep === 0 && (
                      <BasicInfoStep formData={formData} onChange={updateFormData} errors={errors} />
                    )}
                    {currentStep === 1 && (
                      <DataCollectionStep formData={formData} onChange={updateFormData} />
                    )}
                    {currentStep === 2 && (
                      <DataUsageStep formData={formData} onChange={updateFormData} />
                    )}
                    {currentStep === 3 && (
                      <UserRightsStep formData={formData} onChange={updateFormData} />
                    )}
                    {currentStep === 4 && (
                      <ReviewStep
                        formData={formData}
                        sections={sections}
                        policyTitle={policyTitle}
                        onFormChange={updateFormData}
                        onExportPDF={handleExportPDF}
                        onExportJSON={handleExportJSON}
                        onPublish={handlePublish}
                        publishing={publishing}
                      />
                    )}

                    {/* Navigation */}
                    <div className="flex items-center justify-between mt-6 pt-5 border-t border-gray-100 dark:border-gray-800">
                      <Button
                        variant="ghost"
                        onClick={currentStep === 0 ? () => navigate('/') : handleBack}
                        leftIcon={<ArrowLeft className="size-4" />}
                      >
                        {currentStep === 0 ? 'Home' : 'Back'}
                      </Button>
                      {currentStep < 4 && (
                        <Button onClick={handleNext} rightIcon={<ArrowRight className="size-4" />}>
                          Continue
                        </Button>
                      )}
                    </div>
                  </div>

                  {/* Mobile preview toggle */}
                  <div className="lg:hidden mt-4">
                    <button
                      type="button"
                      onClick={() => setPreviewOpen(v => !v)}
                      className="w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-gray-200 dark:border-gray-700 text-sm text-gray-600 dark:text-gray-400 bg-white dark:bg-gray-900 hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                    >
                      {previewOpen ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
                      {previewOpen ? 'Hide preview' : 'Show policy preview'}
                    </button>
                    {previewOpen && (
                      <div className="mt-3">
                        <GeneratorPreview
                          title={policyTitle}
                          sections={sections}
                          companyName={formData.companyName}
                          effectiveDate={formData.effectiveDate}
                        />
                      </div>
                    )}
                  </div>
                </div>

                {/* Desktop preview panel */}
                <div className="hidden lg:block">
                  <div className="sticky top-[120px]">
                    <div className="flex items-center gap-2 mb-3">
                      <Eye className="size-4 text-gray-400" />
                      <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Live preview</p>
                    </div>
                    <GeneratorPreview
                      title={policyTitle}
                      sections={sections}
                      companyName={formData.companyName}
                      effectiveDate={formData.effectiveDate}
                    />
                  </div>
                </div>
              </div>
            </div>
          </>
        )}

        {/* My Policies view */}
        {isMyPolicies && (
          <div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 lg:py-8">
            <div className="mb-6">
              <h1 className="text-xl font-bold text-gray-900 dark:text-white">My policies</h1>
              <p className="text-sm text-gray-400 mt-1">Policies you created with the generator. Click to edit any section.</p>
            </div>
            <MyPoliciesPanel
              onEdit={id => { setView({ type: 'edit', policyId: id }); window.scrollTo({ top: 0 }) }}
              onNewPolicy={() => setView('generator')}
            />
          </div>
        )}

        {/* Policy editor view */}
        {editingPolicy && (
          <div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 lg:py-8">
            <PolicyEditor
              policyId={editingPolicy}
              onBack={() => setView('my-policies')}
            />
          </div>
        )}
      </div>
    </>
  )
}
